version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks:
    - spring-cloud-network
   

  web:
    build: ./core
    ports:
    - "1000-2000:8080"
    networks:
    - spring-cloud-network
    depends_on:
    - rabbitmq
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - SERVER=http://localhost
    - EMAIL=noreply.openszz@gmail.com
    - PWD=Aa30011992
  

  app:
    build: ./gui
    ports:
    - "8081:8080"
    networks:
    - spring-cloud-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  spring-cloud-network:
   driver: bridge
    

    
    






